apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.12.1
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
  - name: master
    count: 1
#    volumeClaimTemplates:
#    - metadata:
#        name: elasticsearch-data
#      spec:
#        accessModes:
#        - ReadWriteOnce
#        resources:
#          requests:
#            storage: 5Gi
#        storageClassName: local-path
    config:
      node.store.allow_mmap: false
      node.roles: ["master"]
#      node.roles: ["master", "data", "ingest", "ml"]
  - name: data
    count: 2
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: local-path
    config:
      node.store.allow_mmap: false
      node.roles: ["data"]
#      node.roles: ["master", "data", "ingest", "ml"]
#  - name: ingest
#    count: 1
#    volumeClaimTemplates:
#    - metadata:
#        name: elasticsearch-data
#      spec:
#        accessModes:
#        - ReadWriteOnce
#        resources:
#          requests:
#            storage: 5Gi
#        storageClassName: local-path
    config:
      node.store.allow_mmap: false
      node.roles: ["ingest"]
#      node.roles: ["master", "data", "ingest", "ml"]