apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-nas
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
volumeBindingMode: WaitForFirstConsumer
parameters:
  backendType: "ontap-nas"
  #  fsType: "ext4"
